name = "crypto-ecosystem-research-v2-final"
main = "_worker.js"
compatibility_date = "2026-10-04"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "crypto-ecosystem-research"
database_id = "35541318-dce9-4cc4-a358-fa09efcd7804"
